### ISSUE TITLE
Exception on paste: `Invocation of 'paste' operation for specific caret is not supported`

### ISSUE THREAD

**Issue by tomsquest** [holgerbrandl/pasteimages#19]
Just copy/paste some text in a typescript file (non markdown).

- Plugin version: 1.2.3
- Intellij 2019.1.3

Stack trace:
```java
java.lang.AssertionError: Invocation of 'paste' operation for specific caret is not supported
	at com.intellij.codeInsight.editorActions.PasteHandler.doExecute(PasteHandler.java:54)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:219)
	at img2md.PasteImageHandler.doExecute(PasteImageHandler.java:87)
	at img2md.PasteImageHandler.execute(PasteImageHandler.java:63)
	at com.intellij.openapi.editor.impl.EditorImpl.lambda$handleDrop$17(EditorImpl.java:4548)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.impl.EditorImpl.handleDrop(EditorImpl.java:4528)
	at com.intellij.openapi.editor.impl.EditorImpl$MyTransferHandler.importData(EditorImpl.java:4573)
	at javax.swing.TransferHandler$DropHandler.drop(TransferHandler.java:1545)
	at java.awt.dnd.DropTarget.drop(DropTarget.java:455)
	at javax.swing.TransferHandler$SwingDropTarget.drop(TransferHandler.java:1283)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:538)
	at sun.awt.X11.XDropTargetContextPeer.processDropMessage(XDropTargetContextPeer.java:184)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:852)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:776)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.awt.Component.dispatchEventImpl(Component.java:4754)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4609)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4471)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by holgerbrandl** [comment]
Is the problem reproducible?

**Comment by pawelkuras** [comment]
> Is the problem reproducible?

I couldn't reproduce it, but resembles [issue-20](https://github.com/holgerbrandl/pasteimages/issues/20)

**Comment by tomsquest** [comment]
Not managed to reproduce. So far, it only happened 3 or 4 times, when doing "rogue" copy-paste. 
Will try to be more vigilant.

@holgerbrandl I close this issue and will re-open if it arise again.

**Comment by holgerbrandl** [comment]
Reopened because also reported under #20
